services:
  rysen_backend:
    image: rysen_sdk:arm64_deploy
    build:
      context: ..
      dockerfile: docker/Dockerfile.rysen_sdk.arm64
    container_name: rysen_sdk_env
    restart: always
    privileged: true
    network_mode: "host"
    ipc: host

    # 实时性增强（核心优化：确保 C++ 控制线程能拿到 90+ 优先级）
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99     # 允许容器内进程设置最高 99 的实时优先级
      memlock: -1    # 锁定内存，防止系统将控制进程置换到 Swap 导致延迟抖动
    volumes:
      - /dev:/dev
      # 把树莓派硬盘上的代码挂载进容器
      - ../..:/workspace
      - build_cache:/workspace/build
    working_dir: /workspace/examples/ros2

    # 4. 环境配置：统一时区和 ROS2 域控
    environment:
      - ROS_DISTRO=humble
      - TZ=Asia/Shanghai
      - ROS_DOMAIN_ID=111

    # 自动执行环境配置和启动脚本
    command: >
      /bin/bash -c "source /opt/ros/humble/setup.bash && 
      source /workspace/examples/ros2/install/setup.bash && 
      ./start_choreography_backend.sh"

    logging:
      driver: "json-file"
      options:
        max-size: "30m"   # 每个日志文件最大 30MB
        max-file: "3"     # 最多保留 3 个滚动日志

volumes:
  build_cache: # 定义编译缓存持久化卷